import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { ReactNode } from "react";
import {
  Box,
  Flex,
  Avatar,
  HStack,
  Link,
  IconButton,
  Button,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuDivider,
  useDisclosure,
  useColorModeValue,
  Stack,
  Text,
} from "@chakra-ui/react";
import { HamburgerIcon, CloseIcon } from "@chakra-ui/icons";
import NextLink from "next/link";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

const Links = ["about"];

const NavLink = ({ children }: { children: any }) => (
  <Link
    px={2}
    py={1}
    rounded={"md"}
    _hover={{
      textDecoration: "none",
      bg: useColorModeValue("gray.200", "gray.700"),
    }}
    href={children}
    textTransform={"capitalize"}
  >
    {children}
  </Link>
);

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Sentimetrics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <>
          <Box bgColor="white" px={[3, 10]}>
            <Flex h={16} alignItems={"center"} justifyContent={"space-between"}>
              <Flex alignItems={"center"}>
                <NextLink href="/">
                  <Text fontWeight={"bold"} color="#05af6e" fontSize="x-large">
                    SentiMetrics
                  </Text>
                </NextLink>
              </Flex>
              <IconButton
                size={"md"}
                icon={isOpen ? <CloseIcon /> : <HamburgerIcon />}
                aria-label={"Open Menu"}
                display={{ md: "none" }}
                onClick={isOpen ? onClose : onOpen}
              />
              <Box>
                {Links.map((link) => (
                  <NavLink key={link}>{link}</NavLink>
                ))}
              </Box>
              <Button
                bg={"#05AF6E"}
                _hover={{
                  backgroundColor: "#dfedeb",
                  color: "#000",
                }}
                onClick={() => router.push("/dashboard")}
                color={"white"}
              >
                Visit Dashboard
              </Button>
            </Flex>

            {isOpen ? (
              <Box pb={4} display={{ md: "none" }}>
                <Stack as={"nav"} spacing={4}>
                  {Links.map((link) => (
                    <NavLink key={link}>{link}</NavLink>
                  ))}
                </Stack>
              </Box>
            ) : null}
          </Box>
        </>
      </main>
    </>
  );
}
