import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { ReactNode } from "react";
import {
  Box,
  Flex,
  Avatar,
  HStack,
  Link,
  IconButton,
  Button,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  MenuDivider,
  useDisclosure,
  useColorModeValue,
  Stack,
  Text,
  Heading,
} from "@chakra-ui/react";
import { HamburgerIcon, CloseIcon } from "@chakra-ui/icons";
import NextLink from "next/link";
import { useRouter } from "next/router";

import Footer from "components/Footer";
import FeatureSection from "components/FeatureSection";
const inter = Inter({ subsets: ["latin"] });

const Links = ["about", "team", "contact"];

const NavLink = ({ children }: { children: string }) => (
  <Link
    px={2}
    py={1}
    rounded={"md"}
    _hover={{
      textDecoration: "none",
      bg: useColorModeValue("gray.200", "gray.700"),
    }}
    href={children}
    textTransform={"capitalize"}
  >
    {children.replace(/^./, (str) => str.toUpperCase())}
  </Link>
);

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Sentimetrics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box px={[3, 10]}>
          <Flex h={16} alignItems={"center"} justifyContent={"space-between"}>
            <Flex alignItems={"center"}>
              <NextLink href="/">
                <Text fontWeight={"bold"} color="#05af6e" fontSize="x-large">
                  SentiMetrics
                </Text>
              </NextLink>
            </Flex>
            <IconButton
              size={"md"}
              icon={isOpen ? <CloseIcon /> : <HamburgerIcon />}
              aria-label={"Open Menu"}
              display={{ md: "none" }}
              onClick={isOpen ? onClose : onOpen}
            />
            <HStack gap={2}>
              {Links.map((link) => (
                <NavLink key={link}>{link}</NavLink>
              ))}
            </HStack>
            <Button
              bg={"#05AF6E"}
              _hover={{
                backgroundColor: "green.500",
              }}
              onClick={() => router.push("/dashboard")}
              color={"white"}
            >
              View Dashboard
            </Button>
          </Flex>

          {isOpen ? (
            <Box pb={4} display={{ md: "none" }}>
              <Stack as={"nav"} spacing={4}>
                {Links.map((link) => (
                  <NavLink key={link}>{link}</NavLink>
                ))}
              </Stack>
            </Box>
          ) : null}
        </Box>
        <Box>
          <Stack
            as={Box}
            textAlign={"center"}
            spacing={{ base: 8, md: 14 }}
            py={{ base: 20, md: 36 }}
          >
            <Heading
              fontWeight={700}
              fontSize={{ base: "2xl", sm: "4xl", md: "6xl" }}
              lineHeight={"110%"}
            >
              Make money from <br />
              <Text as={"span"} color={"green.400"}>
                your audience
              </Text>
            </Heading>
            <Text>
              Monetize your content by charging your most loyal readers and
              reward them loyalty points.
            </Text>
            <Stack
              direction={"column"}
              spacing={3}
              align={"center"}
              alignSelf={"center"}
              position={"relative"}
            >
              <Button
                colorScheme={"green"}
                bg={"green.400"}
                px={10}
                py={6}
                _hover={{
                  bg: "green.500",
                }}
              >
                View Dashboard
              </Button>
              <Button variant={"link"} colorScheme={"blue"} size={"sm"}>
                Learn more
              </Button>
            </Stack>
          </Stack>
        </Box>
        <FeatureSection />
        <Footer />
      </main>
    </>
  );
}
